### ISSUE TITLE
Feature Request (SaaS): Generic Application Types

### ISSUE THREAD

**Issue by h0bbel** [kacole2/JumpSquares#1]
It would be great to have a few generic application types available for those small vendors that don't really merit their own logo/application type.

Examples:
Generic Network
Generic Application/Service

That way we could add the jumpsquares, but not having to select a clearly wrong application type/icon.

Capish?

**Comment by kacole2** [comment]
I have added the following images:
Generic: Bug Tracker
Generic: Cloud
Generic: Dashboard
Generic: Database
Generic: Gears
Generic: Layers
Generic: Network
Generic: Network: Core Switch
Generic: Network: Firewall
Generic: Network: Proxy Filter
Generic: Network: Router
Generic: Network: Switch
Generic: OS: Linux
Generic: OS: Mac
Generic: OS: Windows
Generic: Printer
Generic: Server
Generic: Server: Anti-Virus
Generic: Server: Apple
Generic: Server: LDAP
Generic: Server: Linux
Generic: Server: Windows
Generic: UPS
Generic: WiFi
